name: test

on:
  pull_request:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  go-test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    secrets: inherit
    with:
      go-version: latest
  go-lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
    secrets: inherit
  go-build:
    needs: [go-test, go-lint]
    uses: lrstanley/.github/.github/workflows/lang-go-release.yml@master
    secrets: inherit
    with:
      has-ghcr: true
      upload-artifacts: true
  docker-test:
    needs: [go-test, go-lint]
    uses: lrstanley/.github/.github/workflows/docker-release.yml@master
    secrets: inherit
